<?php use Snowdog\Academy\Model\Book;

require_once(__DIR__ . '/../../common/header.phtml');
?>
<?php if (isset($_SESSION['flash'])): ?>
    <p class="bg-info"><?= $_SESSION['flash'] ?></p>
    <?php unset($_SESSION['flash']) ?>
<?php endif ?>
<section id="books_import" class="padded">
    <form class="form-horizontal" method="POST" action="/admin/import_file" enctype="multipart/form-data">
        <div class="form-group">
            <label for="file" class="col-sm-1 control-label">File:</label>
            <div class="col-sm-10">
                <input type="file" name="file" required/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-2">
                <button type="submit" class="btn btn-primary" value="import">Import books</button>
            </div>
        </div>
    </form>
</section>